datamart:
  target: dev
  outputs:
    dev:
      type: postgres
      host: odp-postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: datamart
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
